# Based on https://stackoverflow.com/a/61706020
name: Redeploy GitHub pages

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl \
            --fail \
            --no-progress-meter \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
